### ISSUE TITLE
Relationship between sparse/0 and sparse/1

### ISSUE THREAD

**Issue by Ioksiong** [maturk/dn-splatter#100]
Thank you for your great work! 
When I run `convert_colmap`, I get two folders, sparse/0 and sparse/1. I noticed that sparse/1 has normal-sized files, while sparse/0 has files that are too small (less than 1M). What is the relationship between sparse/0 and sparse/1, and should I replace sparse/0 with the contents of sparse/1 then continue with the following instructions?
![图片](https://github.com/user-attachments/assets/977641a7-df3e-4398-a98f-42ff7d139cd0)

**Comment by maturk** [comment]
Hi @Ioksiong, could you tell me if your dataset already had the `sparse/0` folder before running the convert_colmap script? Or have you ran the script multiple times? The `sparse/x` folder denotes the sparse SfM reconstruction generated by COLMAP. The number `x` denotes the reconstruction number, and it is possible to have many since you can run colmap as many times as you want, each time it will create a new `x` folder. 

So did you run the script multiple times, or did the dataset already come with a sparse/0 folder? Any more details would help me.

**Comment by Ioksiong** [comment]
> Hi @Ioksiong, could you tell me if your dataset already had the `sparse/0` folder before running the convert_colmap script? Or have you ran the script multiple times? The `sparse/x` folder denotes the sparse SfM reconstruction generated by COLMAP. The number `x` denotes the reconstruction number, and it is possible to have many since you can run colmap as many times as you want, each time it will create a new `x` folder.
> 
> So did you run the script multiple times, or did the dataset already come with a sparse/0 folder? Any more details would help me.
Thank you for your reply!
I can confirm that I only ran `convert_colmap` once; and the format of my original data was data_root/images/xxx.jpg, without sparse/0. Additionally, I noticed that for the other parts of my dataset that I collected, running the same convert_colmap command only generated sparse/0 without sparse/1. I really don't know why sometimes running convert_colmap once generates both sparse/0 and sparse/1.

**Comment by maturk** [comment]
> > Hi @Ioksiong, could you tell me if your dataset already had the `sparse/0` folder before running the convert_colmap script? Or have you ran the script multiple times? The `sparse/x` folder denotes the sparse SfM reconstruction generated by COLMAP. The number `x` denotes the reconstruction number, and it is possible to have many since you can run colmap as many times as you want, each time it will create a new `x` folder.
> > So did you run the script multiple times, or did the dataset already come with a sparse/0 folder? Any more details would help me.
> 
> Thank you for your reply! I can confirm that I only ran `convert_colmap` once; and the format of my original data was data_root/images/xxx.jpg, without sparse/0. Additionally, I noticed that for the other parts of my dataset that I collected, running the same convert_colmap command only generated sparse/0 without sparse/1. I really don't know why sometimes running convert_colmap once generates both sparse/0 and sparse/1.

Yes, if you only ran it once it should only make a single sparse/0 folder. But it is possible maybe you already ran COLMAP prior? Note, if you already have a COLMAP sparse reconstruction (like sparse/0 folder), you do not need to run convert_colmap again.  The `convert_colmap` script simply runs COLMAP for you and does undistortion + camera pose estimation. You can manually do this step as well, I just made the script for convenience.
