### ISSUE TITLE
missing normals in process_sai mode

### ISSUE THREAD

**Issue by soeroesg** [maturk/dn-splatter#16]
I am trying to process a sequence recorded by SPAI-Rec following the [README](https://github.com/maturk/dn-splatter?tab=readme-ov-file#custom-data), but the normals are missing. How can I trigger the generation of normals from the depth map?

**Comment by maturk** [comment]
Hi @soeroesg, thanks for your interest in the project. To generate pseudo-ground truth normal maps, you can use the [omnidata](https://github.com/EPFL-VILAB/omnidata) model to generate them for your dataset images. 

First download the model weights with:
`python dn_splatter/data/download_scripts/download_omnidata.py`

Then run inference with your dataset images using the script:
`python dn_splatter/scripts/normals_from_pretrain.py --data-dir [PATH_TO_ROOT_OF_SAI_DATA]`

This will generate a new folder called `/normals_from_pretrain` inside the dataset directory.

To train with these monocular normal estimates, use the flag `--pipeline.model.normal-supervision mono` when  running the `ns-train dn-splatter` command.  An example command that enables sensor depth supervision and normal supervision with monocular estimates is given here:

```
ns-train dn-splatter --data PATH_TO_DATA \
                 --pipeline.model.use-depth-loss True \
                 --pipeline.model.sensor-depth-lambda 0.2 \
                 --pipeline.model.use-depth-smooth-loss True \
                 --pipeline.model.use-normal-loss True \
                 --pipeline.model.normal-supervision mono\
```

Alternatively, if you do not want to use monocular normal estimates as supervision, you can also try out the `--pipeline.model.normal-supervision depth` flag which should also work; however, I suspect its performance will be a bit worse. 

If using the SpectacularAi Rec application and a phone with a Lidar/ToF sensor, then you can also enable the depth loss flags `--pipeline.model.use-depth-loss True --pipeline.model.sensor-depth-lambda 0.2` for results similar to the ones shown on the website (all captured causally with an iPhone 13 Pro model).

Let me know if you have any more questions. Thanks!

**Comment by maturk** [comment]
If you only want to train with normals generated from the depth map, then the `--pipeline.model.normal-supervision depth` does this already. It uses rendered depth maps during training to generate normal estimates; however, it does not save these into any folder or directly. During development, we also tested generating normal estimates from real sensor data (e.g. kinect sensor or iPhone depth maps); however, this resulted in quite poor and noisy estimates. Therefore, we currently only offer the option for normal supervision with 1) rendered depths and 2) monocular normal estimates.

**Comment by soeroesg** [comment]
I see, thanks for the explanation. By reading the code I thought the normals will be generated also from the real depth maps but then the program crashed when it did not find any normal maps. I will then try to generate normal maps with omnidata.

Just out of curiosity, can we switch off the normal supervision completely and rely only on depth supervision? I could not find a flag combination for depth only. (use-normal-loss False is still trying to load normal maps)

**Comment by maturk** [comment]
> I see, thanks for the explanation. By reading the code I thought the normals will be generated also from the real depth maps but then the program crashed when it did not find any normal maps. I will then try to generate normal maps with omnidata.
> 
> Just out of curiosity, can we switch off the normal supervision completely and rely only on depth supervision? I could not find a flag combination for depth only. (use-normal-loss False is still trying to load normal maps)

Yes, it is possible to prevent loading normals all together. It is just a bit hidden right now in the dataparsers. You can use the flag `--load-normals False` to disable loading normals in the dataparser/dataloading stage. You can use it as follows:

```
ns-train dn-splatter --pipeline.model.use-depth-loss True --pipeline.model.sensor-depth-lambda 0.2 --pipeline.model.use-depth-smooth-loss True --pipeline.model.use-normal-loss False --data [PATH_TO_DATA] --load-normals False
```
Make sure to put this flag at the very end (after the `--data` flag). There are quite many flags and I hope to simplify some of them.

**Comment by soeroesg** [comment]
is it possible that his option was removed over time? I tried the exact command above and I get the error
Unrecognized or misplaced options: --load-normals

**Comment by maturk** [comment]
I see. It seems that I need to specify the dataparser name so that these dataparser specific flags (like `--load-normals `or `--load-pcd-normals` or `--normal-format`) are applied. If using custom data, like the SAI processed data, then the dataparser name is `normal-nerfstudio` which is an extension of the basic dataparser from nerfstudio but with a few added options to deal with these extra normal conventions in this project. 

To use it, try the command below:

`ns-train dn-splatter [model specific options...] normal-nerfstudio --data [path_to_data] --load-normals False`

**Comment by soeroesg** [comment]
indeed, adding `normal-nerfstudio` before the `--data` makes it work. thank you!
