### ISSUE TITLE
Where you use 3DGS in your code? 

### ISSUE THREAD

**Issue by cdfan0627** [maturk/dn-splatter#19]
Thank you very much for your work. 
Could you please explain where 3DGS is used in your code? It looks different from typical 3DGS code.

**Comment by maturk** [comment]
Hi @cdfan0627, this project is an extension of the [splatfacto](https://docs.nerf.studio/nerfology/methods/splat.html) model from Nerfstudio. Specifically, this repo extends (subclasses splatfaco) with features like depth supervision, normal supervision, and other regularization (like smoothness constraints) as well as basic mesh extraction.
