### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by ChenLu-china** [maturk/dn-splatter#2]
When I use self data to reconstruct with coolermap tag, I got OOM problem after three iterations, but I can successfully run with Office0 of replica.

Command I used 
`ns-train dn-splatter --pipeline.model.use-depth-loss True --pipeline.model.sensor-depth-lambda 0.2 --pipeline.model.use-depth-smooth-loss True --pipeline.model.use-normal-loss True --pipeline.model.normal-supervision mono  coolermap --data /home/chenlu/luchen/dn-splatter/datasets/0322_1  --load-normals True`

Error
![20240408-182507](https://github.com/maturk/dn-splatter/assets/74493433/a1c2d0c0-0515-4058-bea4-056d182507d1)

**Comment by ChenLu-china** [comment]
> Hi @ChenLu-china, is it possible if you share your dataset with me (processed so it has colmap/sparse/0 database information), so I can also check. I am not entirely sure what the problem is from the error message, because it seems that the failure comes inside the "gsplat" package ([this](https://github.com/nerfstudio-project/gsplat) package to be more specific, which is a dependency for dn-splatter).
> 
> One thing to note is that you will require more VRAM if your dataset is very large. Replica dataset (with my version of the replica dataparser) only loads around 60 or so input frames during training. But if your dataset is very large, this could cause memory issues as well.

Thanks for your reply! I will send a package with my data to your email. I also try to set  `load_every` to 25 and load around 60 images, But still oom.

**Comment by ChenLu-china** [comment]
> Hi @ChenLu-china, is it possible if you share your dataset with me (processed so it has colmap/sparse/0 database information), so I can also check. I am not entirely sure what the problem is from the error message, because it seems that the failure comes inside the "gsplat" package ([this](https://github.com/nerfstudio-project/gsplat) package to be more specific, which is a dependency for dn-splatter).
> 
> One thing to note is that you will require more VRAM if your dataset is very large. Replica dataset (with my version of the replica dataparser) only loads around 60 or so input frames during training. But if your dataset is very large, this could cause memory issues as well.

I have sent an email to you. If you do not receive it, you can also download from here https://drive.google.com/file/d/1aSKF3sCvIshWVCBQUPHvsHeRr4BShrYp/view?usp=drive_link. Thx!

**Comment by ChenLu-china** [comment]
> Hi @ChenLu-china, thanks for the dataset. I notice that it has the same 16 images repeated for many times, is this intended?
> 
> Regardless, I made a slight change to the default settings in coolermap dataparser.
> 
> Can you try training with the command `ns-train dn-splatter --pipeline.model.use-normal-loss True --pipeline.model.normal-supervision mono coolermap --data [PATH_TO/HomeStay_0322/] --load-normals True`.
> 
> Remember, don't forget to generate monocular normal estimates for the dataset before (if you wish to train with --pipeline.model.normal-supervision mono, instead of --pipeline.model.normal-supervision depth). You can do so by simply running this script:
> 
> `python dn_splatter/scripts/normals_from_pretrain.py --data-dir [PATH_TO/HomeStay_0322/]`
Thx, I will try it later, and feedback asap!

**Comment by pdxmusic** [comment]
Hi everyone, I also had this issue while training 300 pictures 1920x1080 on a 4090 24gb, it went out of memory for about 8gb.

I "steeled" @ChenLu-china dataset from this issue and I made it work correctly.  

My question is: what's the best way to don't go OOM? Is it better to reduce the number of pictures or the size of the images?
Is there anything else I can do to avoid OOM while using 300 pictures?

**Comment by ChenLu-china** [comment]
> Hi everyone, I also had this issue while training 300 pictures 1920x1080 on a 4090 24gb, it went out of memory for about 8gb.
> 
> I "steeled" @ChenLu-china dataset from this issue and I made it work correctly.
> 
> My question is: what's the best way to don't go OOM? Is it better to reduce the number of pictures or the size of the images? Is there anything else I can do to avoid OOM while using 300 pictures?

I guess your log shows the step `"Initialising normals... (slow) this operation is not batched yet"`?

**Comment by pdxmusic** [comment]
Yes, with both datasets, mine and yours, while having more ram on my GPU I was able to generate a ply from your dataset but I'm not able to generate it using mine.

Your dataset is: 1104 pictures 1000x1000 
Mine is: 300 pictures 1920x1080

**Comment by maturk** [comment]
> > Hi everyone, I also had this issue while training 300 pictures 1920x1080 on a 4090 24gb, it went out of memory for about 8gb.
> > I "steeled" @ChenLu-china dataset from this issue and I made it work correctly.
> > My question is: what's the best way to don't go OOM? Is it better to reduce the number of pictures or the size of the images? Is there anything else I can do to avoid OOM while using 300 pictures?
> 
> I guess your log shows the step `"Initialising normals... (slow) this operation is not batched yet"`?

Hi. The initialization of normals refers to initialising the gaussian covariance matrices and scales according to estimated SfM point cloud directions. In the original 3GDS work, the quaternions of each Gaussian is set randomly. However, in this work, I initialize the quaternion to align with estimates from Open3D normals. This process is slow, currently not batched/vectorized in my code (apologies for this I just havent found a way to do that). Please disable this feature with the --load-pcd-normals False flag.

**Comment by maturk** [comment]
Hi @ChenLu-china and @pdxmusic, I tried to address the speed issues in #6, this should fix the OOM issue as well. Let me know if it still persists.

**Comment by ChenLu-china** [comment]
> Hi @ChenLu-china and @pdxmusic, I tried to address the speed issues in #6, this should fix the OOM issue as well. Let me know if it still persists.

Thanks! I will pull the code and try it again.
