### ISSUE TITLE
How can i get a texture

### ISSUE THREAD

**Issue by yang1hu** [maturk/dn-splatter#30]
Thanks for your great project! I have got the mesh successfully. I wanna know if there is any way to get the texture, thank you very mush

**Comment by XuqianRen** [comment]
Hi, @yang1hu we add open3d tsdf mesh extraction in this branch https://github.com/maturk/dn-splatter/tree/fix_mono_depth, it can get texture mesh. We will merge this branch to main soon.

**Comment by maturk** [comment]
You can use the `gs-mesh o3dtsdf --load-config ... --output-dir ...` to get an okay textured mesh. But the texturing is not optimized, so it is not as good as e.g. SuGaR texture.
