### ISSUE TITLE
Viewing methods for trained models

### ISSUE THREAD

**Issue by wangjinhoon** [maturk/dn-splatter#32]
Hello, thank you for sharing the great code.

Is there a way to visualize a trained model similar to Navigation in SIBR Viewers using 3D Gaussian splatting?

**Comment by maturk** [comment]
Hi @wangjinhoon, you can view the model using the nerfstudio viewer (called viser) during and after training. During training, the ns-train command spawns the server on the localhost:7007 address on your webbrowser. You can also load a trained model using the `ns-viewer --load-config [path to trained model config]` command.

Let me know if you have any questions! Thanks

**Comment by wangjinhoon** [comment]
Thank you for the quick response.
