### ISSUE TITLE
Mesh Quality Discrepancy Using Scannet++

### ISSUE THREAD

**Issue by Valentina-Zhang** [maturk/dn-splatter#35]
Hi~Thanks for sharing the code!

I am using scene 8b5caf3398 from the Scannet++ dataset for training but the mesh extraction has not yielded the expected results.

First, I processed data into COLMAP format, and generated omnidata normals and mono-depth estimates.

Then, I trained the model for 30k iterations:
`ns-train dn-splatter --pipeline.model.use-depth-loss True --pipeline.model.mono-depth-lambda 0.2 --pipeline.model.use-depth-smooth-loss True --pipeline.model.use-normal-loss True --pipeline.model.normal-supervision mono coolermap --data [DATASET_PATH] --load_normals True
`

Finally, I attempted mesh extraction following your suggestions:
`gs-mesh dn --load-config [PATH] --output-dir [PATH]
`

But the results were very unsatisfactory:

https://github.com/maturk/dn-splatter/assets/65186462/6a3dc84d-c54e-450e-b9d3-4264f1c11295

I tried other methods and found the sugar-coarse method performs better:
`gs-mesh sugar-coarse --load-config [PATH] --output-dir [PATH]
`

https://github.com/maturk/dn-splatter/assets/65186462/c5579dfb-a246-4c9e-bcad-25ca309f4b38

However, it still falls short of the quality shown in your paper. I am not sure if I followed the same settings as your paper.

Could you provide some guidance or suggestions to improve the quality of the mesh to more closely resemble the results in your paper? 

Thanks!

**Comment by maturk** [comment]
Hi @Valentina-Zhang, can you use the dedicated `scannetpp` dataparser (instead of `coolermap`) when using scannett data? We use the iPhone depth sequences "b20a261fdf" and "8b5caf3398" from ScanNet++. In the paper all results, except table 5 in the ablations, use real sensor depths for supervision. The performance of monocular supervision is unfortunately not on par with sensor supervision on difficult and larger indoor scenes. 

Can you try the command: 
```
ns-train dn-splatter 
                 --pipeline.model.use-depth-loss True \
                 --pipeline.model.sensor-depth-lambda 0.2 \
                 --pipeline.model.use-depth-smooth-loss True \
                 --pipeline.model.use-normal-loss True \
                 --pipeline.model.normal-supervision (mono/depth) \
                 scannetpp --data PATH_SCANNET_DATA_ROOT --sequence 8b5caf3398
```

More options specific to the scannet++ dataset can be found in the configs [here](https://github.com/maturk/dn-splatter/blob/bc83595b0685f0fba0f0b440d510bb9123a8fdb2/dn_splatter/data/scannetpp_dataparser.py#L40)

**Comment by Sugar55888** [comment]
> Hi @Valentina-Zhang, can you use the dedicated `scannetpp` dataparser (instead of `coolermap`) when using scannett data? We use the iPhone depth sequences "b20a261fdf" and "8b5caf3398" from ScanNet++. In the paper all results, except table 5 in the ablations, use real sensor depths for supervision. The performance of monocular supervision is unfortunately not on par with sensor supervision on difficult and larger indoor scenes.
> 
> Can you try the command:
> 
> ```
> ns-train dn-splatter 
>                  --pipeline.model.use-depth-loss True \
>                  --pipeline.model.sensor-depth-lambda 0.2 \
>                  --pipeline.model.use-depth-smooth-loss True \
>                  --pipeline.model.use-normal-loss True \
>                  --pipeline.model.normal-supervision (mono/depth) \
>                  scannetpp --data PATH_SCANNET_DATA_ROOT --sequence 8b5caf3398
> ```
> 
> More options specific to the scannet++ dataset can be found in the configs [here](https://github.com/maturk/dn-splatter/blob/bc83595b0685f0fba0f0b440d510bb9123a8fdb2/dn_splatter/data/scannetpp_dataparser.py#L40)
@maturk 
Hello, I used the above command to train the 8b5caf3398 sequence in the scan++dataset. But during testing, it was found that the generated Gaussian points were quite messy, and the rendered depth map and normal map surfaces were not very smooth. Is this normal?
![image](https://github.com/maturk/dn-splatter/assets/161268635/62215dad-982b-4b3f-9d37-a91767eb4f1d)
![image](https://github.com/maturk/dn-splatter/assets/161268635/5353e391-6b52-4b7e-98e6-55c6cda4b282)
![image](https://github.com/maturk/dn-splatter/assets/161268635/3cfa8bc7-be74-4601-a92c-2db48b7f6857)

**Comment by Sugar55888** [comment]
And the rgb_psnr is only 12.11 in the json file.
![image](https://github.com/maturk/dn-splatter/assets/161268635/985ec725-e449-40c9-aadc-1e6972c350d5)

**Comment by Yellowshuohahaha** [comment]
I change the version of nerfstudio and gsplat to 1.1.0 and 0.1.11. And the calculation of PNSR is normal.

**Comment by Sugar55888** [comment]
I change the version of nerfstudio and gsplat to 1.1.0 and 0.1.11. And the calculation of PNSR is normal.

**Comment by maturk** [comment]
@Sugar55888, what version of pytorch are you using? There are known issues with pytorch 2.0.1 (I recommend installing pytorch 2.1.2+ if you have an older version). 

I have just tested on the b20a261fdf scene from scannet++ with the following command:

```
ns-train dn-splatter --pipeline.model.use-depth-loss True --pipeline.model.sensor-depth-lambda 0.2 --pipeline.model.use-depth-smooth-loss True --pipeline.model.use-normal-loss True  scannetpp --data ../gstream/datasets/scannetpp/
```

Here are the metrics from ns-eval:
```
{
  "experiment_name": "unnamed",
  "method_name": "dn-splatter",
  "checkpoint": "outputs/unnamed/dn-splatter/2024-06-26_101439/nerfstudio_models/step-000029999.ckpt",
  "results": {
    "rgb_psnr": 21.39521598815918,
    "rgb_psnr_std": 3.4141998291015625,
    "rgb_ssim": 0.8932474851608276,
    "rgb_ssim_std": 0.037611667066812515,
    "rgb_lpips": 0.16607534885406494,
    "rgb_lpips_std": 0.0638774186372757,
    "depth_abs_rel": 0.036066967993974686,
    "depth_abs_rel_std": 0.019739612936973572,
    "depth_sq_rel": 0.02396574430167675,
    "depth_sq_rel_std": 0.022433273494243622,
    "depth_rmse": 0.24497883021831512,
    "depth_rmse_std": 0.10275601595640182,
    "depth_rmse_log": 0.036185991019010544,
    "depth_rmse_log_std": 0.024228833615779877,
    "depth_a1": 0.9641259908676147,
    "depth_a1_std": 0.038147591054439545,
    "depth_a2": 0.986823558807373,
    "depth_a2_std": 0.024890735745429993,
    "depth_a3": 0.9960512518882751,
    "depth_a3_std": 0.009821201674640179,
    "num_rays_per_sec": 128616520.0,
    "num_rays_per_sec_std": 23672480.0,
    "fps": 46.575870513916016,
    "fps_std": 8.572510719299316
  }
}
```

**Comment by maturk** [comment]
> @maturk Hi, I used pytorch 2.0.1 because the readme mentioned that pytorch 2.1.2 may have TypeError: expected size to be one of int or Tuple [int] or Tuple [int, int] or Tuple [int, int, int], but got size with types [<class' numpy. int64 '>,<class' numpy. int64'>] I will upgrade my PyTorch version for testing. Thank you!

I see, yes this is a bit tricky because zoe-depth also has known issues with higher pytorch versions XD But that is only if you want to use zoe-depth. I found these issues also in Nerfstudio, and right now the requirement for Nerfstudio should be torch>=2.1.2. I have noted this in a few issues [here](https://github.com/nerfstudio-project/nerfstudio/issues/3230) and  [here](https://github.com/nerfstudio-project/nerfstudio/issues/3235). I think its due to `@torch_compile()`, although, I have not looked too deeply into it.

**Comment by Sugar55888** [comment]
I compared the performance of two different PyTorch versions of dn-splatter on the 8b5caf3398 sequence in scannet++. I found that their training speed and PNSR are similar, but in PyTorch 2.0.1, the predicted normal vector map is smoother.
![image](https://github.com/maturk/dn-splatter/assets/161268635/83f756a3-e0e1-4fb3-9927-8df4f972696f)
![image](https://github.com/maturk/dn-splatter/assets/161268635/83f756a3-e0e1-4fb3-9927-8df4f972696f)
The right figure shows the prediction results in the dn-splatter with pytorch 2.0.1.

**Comment by maturk** [comment]
> I compared the performance of two different PyTorch versions of dn-splatter on the 8b5caf3398 sequence in scannet++. I found that their training speed and PNSR are similar, but in PyTorch 2.0.1, the predicted normal vector map is smoother. ![image](https://private-user-images.githubusercontent.com/161268635/343205593-83f756a3-e0e1-4fb3-9927-8df4f972696f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTI3NjcsIm5iZiI6MTcxOTQxMjQ2NywicGF0aCI6Ii8xNjEyNjg2MzUvMzQzMjA1NTkzLTgzZjc1NmEzLWUwZTEtNGZiMy05OTI3LThkZjRmOTcyNjk2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxNDM0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWMwNDkwMzEwYmIxN2UwOWEyYzJlMTIwZDRkMzc0YzA1MzgyNGI5ZWExMmFmMDUyMmNiZmRiMzg4M2E0YWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.muhb0jy81z_ulayzLXoSCAmNRuTJml0cdlBK2RzCnE0) The right figure shows the prediction results in the dn-splatter with pytorch 2.0.1.

And what is the left figure? pytorch 2.1.2 and gsplat v1.0.0 and nerfstudio v1.1.3? What is the gsplat and nerfstudio version for the right figure?

**Comment by Sugar55888** [comment]
The left figure is pytorch 2.1.2 and gsplat v1.0.0 and nerfstudio v1.1.3.  And the right figure is pytorch 2.0.1 and gsplat v0.1.11 and nerfstudio v1.1.0.  I use the command as follows:
ns-train dn-splatter 
                 --pipeline.model.use-depth-loss True \
                 --pipeline.model.sensor-depth-lambda 0.2 \
                 --pipeline.model.use-depth-smooth-loss True \
                 --pipeline.model.use-normal-loss True \
                 --pipeline.model.normal-supervision mono \
                 scannetpp --data PATH_SCANNET_DATA_ROOT --sequence 8b5caf3398

**Comment by maturk** [comment]
> The left figure is pytorch 2.1.2 and gsplat v1.0.0 and nerfstudio v1.1.3. And the right figure is pytorch 2.0.1 and gsplat v0.1.11 and nerfstudio v1.1.0. I use the command as follows: ns-train dn-splatter --pipeline.model.use-depth-loss True --pipeline.model.sensor-depth-lambda 0.2 --pipeline.model.use-depth-smooth-loss True --pipeline.model.use-normal-loss True --pipeline.model.normal-supervision mono scannetpp --data PATH_SCANNET_DATA_ROOT --sequence 8b5caf3398

Thank you @Sugar55888, I will look into this more closely.

**Comment by Sugar55888** [comment]
@maturk Thanks for your reply!

**Comment by maturk** [comment]
Hi @Sugar55888. I have fixed the issue now in #49. I was able to replicate your results.

before the fix in the above PR:  "rgb_psnr": 22.428760528564453
<img src="https://github.com/maturk/dn-splatter/assets/30566358/ef2c1766-414e-4d73-a8a3-ff15c6ebeadc" alt="with detach()" width="300" height="300">

after fix in the above PR: "rgb_psnr": 22.47365951538086
<img src="https://github.com/maturk/dn-splatter/assets/30566358/99a4273f-d2de-431e-b567-9d30eecab80a" alt="without detach()" width="300" height="300">

There is very marginal difference in PSNR results, however, the normal smoothness is significantly better. Here I also evaluated on a scene from Replica:

Before the fix in the above PR:
<img src="https://github.com/maturk/dn-splatter/assets/30566358/2807bdbd-1dc8-48d1-9645-2b5c306ffac7" alt="without detach()" width="500" height="300">

After fix in the above PR:
<img src="https://github.com/maturk/dn-splatter/assets/30566358/ff12635a-b331-47b7-831e-686056511f6b" alt="without detach()" width="500" height="300">


Thanks for your interest and helping me debug the code! :)

**Comment by Sugar55888** [comment]
@maturk Thank you for your excellent work!

**Comment by maturk** [comment]
Here is a comparison of expected results using either monocular depth supervision with scale alignment, vs pearson correlation loss, vs sensor depth regularization on mesh reconstruction metrics. 

<img width="514" alt="image" src="https://github.com/user-attachments/assets/07c7ffea-903b-4040-b31b-9a3b1c831504">
