### ISSUE TITLE
Unrecognized options:--skip-colmap-to depths,--skip mono-depth-creation,

### ISSUE THREAD

**Issue by Aur1anna** [maturk/dn-splatter#41]
Hi,thanks for sharing your great work!
I try to use my COLMAP processed dataset and i have data root like this:
![e73820c3197b8177d4abcfa8a7e57875](https://github.com/maturk/dn-splatter/assets/161825526/3fee2651-1970-468b-a96d-3abf68792f7d)
and when i use the script, error shows as below:
![1718033821080](https://github.com/maturk/dn-splatter/assets/161825526/9762c1a4-ad7c-4465-9496-c21acf7f0b08)

Any help would be much appreciated!
thanks

**Comment by maturk** [comment]
@Aur1anna you are just inputting the command wrong in the terminal. Try 
`python dn_splatter/scripts/align_depth.py --data [path_to_data_root]`

You don't need the other ones unless you want to skip colmap or monodepth stages. 
You should choose only one of the following: `--skip-colmap-to-depths ` or `--no-skip-colmap-to-depths`. not both. sorry the readme is not clear.
