### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by efyphil** [maturk/dn-splatter#43]
Hi, I wrote to nerfstudio about the build issue, basically I fixed all the impots and everything came together, here are the imports I changed, hopefully that will help
from gsplat._torch_impl import quat_to_rotmat
from gsplat.project_gaussians import project_gaussians
from gsplat.rasterize import rasterize_gaussians
from gsplat.sh import num_sh_bases, spherical_harmonics
changed it to this
from gsplat.cuda_legacy._torch_impl import quat_to_rotmat
from gsplat import project_gaussians
from gsplat import rasterize_gaussians
from gsplat.cuda_legacy._wrapper import num_sh_bases , spherical_harmonics

**Comment by maturk** [comment]
addressed in #45
