### ISSUE TITLE
How to set "load_depth" false

### ISSUE THREAD

**Issue by Kairui-SHI** [maturk/dn-splatter#62]
Thank you for your great work. 

However, I notice that dn_dataset have such a judgement like if I load depth. How can I turn it off?

![image](https://github.com/user-attachments/assets/8a9ee24a-d41d-41ea-a4c7-200de1e8dce7)

**Comment by maturk** [comment]
There are a few points to make here. 

To disable depth loss during training just use `--pipeline.model.use-depth-loss False `
To disable loading depths, this has to be done in the dataparser stage. Add the `--load-depths False` command after the dataparser specification. Here is an example:

```
ns-train dn-splatter  --pipeline.model.use-depth-loss False  mushroom --data ./path_to_data --load-depths False 
```
Note that the --load-depths command comes after the 'mushroom' keyword which specifies the dataparser. 

Please note that dn-splatter assumes the user is interested in at least depth supervision, so if you just want to turn all features off, you can just use the regular `splatfacto` method from Nerfstudio.

**Comment by Kairui-SHI** [comment]
Thanks for your explanation very much. I got it. That's true not to close depth loss better.

However, when I follow the instruction. set self.opacities on, I got one fault: AttributeError: can't set attribute.
It seems I cannot change the value of self.opacities [here](https://github.com/maturk/dn-splatter/blob/aa754d80b72a484f69e769113c065a6e78deb24b/dn_splatter/dn_model.py#L440)
