### ISSUE TITLE
Mesh + Texture

### ISSUE THREAD

**Issue by didiemme** [maturk/dn-splatter#71]
I've been able to extract mesh using gs-mesh tsdf (commit 811f5cdf342d92d12a9d9a4be185d374c430c184) i was wondering if there is a way to extract texture as well.
Thanks.
d.

**Comment by maturk** [comment]
Hi, 

You can use the `gs-mesh o3dtsdf --load-config ... --output-dir ... ` to get a textured mesh. I recommend this for your case. But the texturing is not optimized, so it is not as good as per say SuGaR texture, but it should be pretty okay (based on traditional mesh texturing). The `gs-mesh dn` method also outputs a texture for the mesh.

**Comment by maturk** [comment]
Here is a quick example training on a replica scene for only 1000 iterations and the output mesh from dn and o3dtsdf:

`gs-mesh dn`:
![dn00](https://github.com/user-attachments/assets/660e8d47-1d60-4c90-91fe-abd1e51bab4e)

`gs-mesh o3dtsdf`:
![o3dtsdf01](https://github.com/user-attachments/assets/1394b121-f232-4a10-9a5a-0aa2b6fa6c0c)
