### ISSUE TITLE
train error： ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by Knni9ht** [maturk/dn-splatter#82]
deviece:win11
installation:
       conda create --name nerfstudio -y python=3.8
       conda activate nerfstudio
       python -m pip install --upgrade pip
       pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
       pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
       git clone https://github.com/maturk/dn-splatter
       cd dn_splatter/
       pip install setuptools==69.5.1
       pip install -e .
after installation,i runed with ns-train dn-splatter,but met errors below:
ImportError: cannot import name 'csrc' from 'gsplat'
.........
ninja: build stopped: subcommand failed.

**Comment by Knni9ht** [comment]
it looks like
![c00270d82cca02c5d2485c366e452f28](https://github.com/user-attachments/assets/dbfcfb75-dd58-4451-8dc4-c75ef12d9cac)

**Comment by maturk** [comment]
@Knni9ht. Looks like something is wrong when trying to build the `gsplat` dependency. 

Can you try running `pip install gsplat==1.0.0` and then ns-train again. 

Alternatively you can attempt to manually install gsplat using the following instructions:
```
git clone --recurse-submodules https://github.com/nerfstudio-project/gsplat/
cd ./gsplat
git checkout c7b0a38
pip install -e .
```
This clones the gsplat repo, switches to the v1.0.0 version, and installs it. Note, this repo currenly only supports gsplat v1.0.0. 

Note, I am not a windows user, so I am not entirely sure what kind of issues the Windows OS can get when installing gsplat. 

Let me know if any of these instructions help. The main thing is just to try and install the gsplat dependency, and make sure it is v1.0.0, then dn-splatter will work for you.

**Comment by Knni9ht** [comment]
@maturk Thanks for your response! It works for me and I begin to train. However,the train process was broken and warned me "CUDA out of mermery" ,even though I only used 750 pic in my 4070ti super. But when I trained in gsplat,it worked well.Do u have any idea about that.

**Comment by maturk** [comment]
dn-splatter needs a bit more memory since it uses depth and/or normal information during training. Not entirely sure how to help you with the OOM memory. I suggest decreasing the number of images being used.

**Comment by seulqxq** [comment]
Hello, I also encountered a similar problem, may I ask what is your version? The following is my version and the error:
gsplat==1.0.0
nerfstudio==1.1.3
torch==2.1.2+cu118
torchvision==0.16.2+cu118
pytorch-lightning==2.0.6
CUDA==11.8

ERROR:
from gsplat import csrc as _C
ImportError: cannot import name 'csrc' from 'gsplat' (/opt/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/gsplat/__init__.py)
........
ImportError: /root/.cache/torch_extensions/py38_cu118/gsplat_cuda/gsplat_cuda.so: cannot open shared object file: No such file or directory
