### ISSUE TITLE
Load pretrained pointcloud model to train

### ISSUE THREAD

**Issue by ferryman123** [maturk/dn-splatter#83]
Hello. I wonder if it is possible to load the 3DGS trained ply model to dnsplatter as the initial training checkpoint. 
That is, convert the following pointcloud format to checkpoint format？
![1729679331229](https://github.com/user-attachments/assets/baa0d25f-8e9c-4e87-8ae2-8a53f3d249ba)
![1729679482189](https://github.com/user-attachments/assets/557aa0bb-3894-4f66-bdba-2b8cbb3f35ce)

**Comment by ferryman123** [comment]
![snipaste_20241023_183420](https://github.com/user-attachments/assets/171450bf-d8ca-472a-b7e5-003c212ff9e4)

**Comment by maturk** [comment]
@ferryman123 do you mean that you are trying to load a gaussian splatting file that has been saved in .ply format as the initial point cloud? This is not supported. You can convert a gaussian file into a normal point cloud (with only xyz data), and use that for initialization.

the "ply_file_path" in this context refers to a normal point cloud file.

**Comment by ferryman123** [comment]
@maturk All right，thankyou, could you tell me how to convert a gaussian file into a normal point cloud (with only xyz data)，I don't know how to do it

**Comment by maturk** [comment]
@ferryman123 I am not sure if there is any readily available tool online to do that or not. I suggest you first inspect the actual code that nerfstudio or other applications do to convert a Gaussian model into a .ply file. e.g. [here](https://github.com/nerfstudio-project/nerfstudio/blob/fc4fc5cb15ad994ea82d8c651c9d42172d890de1/nerfstudio/scripts/exporter.py#L581). You will see that the logic is very simple, you simply read the data from the model like the means, colors, opacities, etc, and write them into a ply file.

For your task, you need to do the inverse, i.e. take a ready made Gaussian .ply file, and simply extract the means and use those directly or then save them to another .ply file containing only the xyz data. 

Hope this helps in your research.

**Comment by ferryman123** [comment]
@maturk  Sorry to bother you again, I converted the Gaussian .ply file to a standard ply file yesterday, but I cannot load the standard ply model to dnsplatter as the initial training checkpoint.
It gives an error again like this:https://github.com/maturk/dn-splatter/issues/83#issuecomment-2432368272

**Comment by ferryman123** [comment]
@maturk Does this mean that using the default option [normal-nerfstudio] ,I need additional data to put into the dataset?
Currently my dataset structure is 
![截图 2024-10-23 22-20-00](https://github.com/user-attachments/assets/d2e42ca7-4b36-40cf-8070-312b77bab3ba)

**Comment by maturk** [comment]
@ferryman123 how is your gaussian ply made in the first place?

**Comment by ferryman123** [comment]
I load the gaussian ply into the blender,then save the new ply file that only contain xyz data 
![截图 2024-10-24 11-13-54](https://github.com/user-attachments/assets/90fe92ff-a365-40bd-b3be-882d8c6b36bb)

**Comment by maturk** [comment]
Does training with dn-splatter work for you? When u try ns-train dn-splatter --data ...? 

Loading ply files as checkpoints does not work.The error you are getting is not related, its an error about not finding some depth files.

**Comment by maturk** [comment]
If you want to use ur xyz ply as initial seed points you need to change path here https://github.com/maturk/dn-splatter/blob/a1268f9101c5c032587db45ffd74b213d8471f62/dn_splatter/data/normal_nerfstudio.py#L445

**Comment by ferryman123** [comment]
@maturk  yes,I change.  I find it not the load ply file problem, because I use the colmap load the ply file to run it also doesnot work.
You say its an error about not finding some depth files,but I put the depth files in the folder like the 
![截图 2024-10-23 22-20-00](https://github.com/user-attachments/assets/df7a85b2-02bb-4a5c-9efd-aee11205126e)

if it means I need other depth file?
and my command is :ns-train dn-splatter --pipeline.model.use-depth-loss True --pipeline.model.depth-lambda 0.5 --pipeline.model.use-normal-loss True --pipeline.model.use-normal-tv-loss True --pipeline.model.normal-supervision mono  --data datasets/data

**Comment by ferryman123** [comment]
Apart from anything else, I would like to know what data structures are required for the dataset of normal-nerfstudio datasparser

**Comment by maturk** [comment]
If you have colmap sparse/0 file, can you instead use the coolermap dataparser? e.g. `ns-train dn-splatter [options] coolermap --data [path_to_data]`.  The dataset should have the sparse/0 folder from colmap.

**Comment by ferryman123** [comment]
@maturk But I want to import a ply file as the initial point cloud instead of using the colmap data structure. And I don't find an option in coolermap datasparser to import ply files like in normal-nerfstudio. https://github.com/maturk/dn-splatter/blob/a1268f9101c5c032587db45ffd74b213d8471f62/dn_splatter/data/normal_nerfstudio.py#L419
