### ISSUE TITLE
How to export train result as ply

### ISSUE THREAD

**Issue by Knni9ht** [maturk/dn-splatter#84]
I want export the train result as a ply file.But the `ns-export` commend did not work.

**Comment by maturk** [comment]
Did you experience some error?

**Comment by Knni9ht** [comment]
On the dn-splatter environment,the `ns-export gaussian-splat` commend didnot do anything.There was nothing happened after I use the commend,just passed,nothing output.

So I switched to gsplat environment. And I used commend`ns-export gaussian-splat --load-config`,but it seemed that the config.yaml was not right.Then I modified the config.yaml from the gsplat training config.yaml.And then it worked.

**Comment by Knni9ht** [comment]
Do you consider to build a standard export process like gsplat?

**Comment by maturk** [comment]
What do you mean that the `ns-export gaussian-splat` did not do anything? Can you please provide more information. The output is generated into a separate file. There is not much output in the actual terminal log, but if you inspect the output folder you will find the splat.ply file there. 

e.g. the command `ns-export gaussian-splat --load-config path_to_/config.yml --output-dir ./my_output`
will generate a new file called ./my_output/splat.ply which is the ply file you want.

**Comment by maturk** [comment]
> Do you consider to build a standard export process like gsplat?

ns-export gaussian-splat already does gaussian splatting export into a .ply file, which is viewable in other applications of viewers.

**Comment by Knni9ht** [comment]
![image](https://github.com/user-attachments/assets/9399bfb6-c5f0-4d94-bdda-67d94b378609)

**Comment by maturk** [comment]
Here are steps to create a splat.ply file:

1) train a model using `ns-train dn-splatter [options]`
2) make a note of where the config.yml file is saved after training. 
3) run `ns-export gaussian-splat --load-config path_to_/config.yml --output-dir ./my_output` and it will create a new file called `/my_output/splat.ply`

**Comment by Knni9ht** [comment]
> ![image](https://private-user-images.githubusercontent.com/103084421/379730050-9399bfb6-c5f0-4d94-bdda-67d94b378609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjYyODcsIm5iZiI6MTcyOTc2NTk4NywicGF0aCI6Ii8xMDMwODQ0MjEvMzc5NzMwMDUwLTkzOTliZmI2LWM1ZjAtNGQ5NC1iZGRhLTY3ZDk0YjM3ODYwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMDMzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDNmMzI3YjRmYTNkOTNkZjEyZGZhNWRlNzA1YTQxOGMxYzY4N2NiMDcyZjdhNzFiOTVmMmQ1MzIxZTU2MTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pOfepkfMXxj_abTLw8m3XTCuAL7or-nUp28bdjOr9nU)

just prinnted nothing

**Comment by maturk** [comment]
> > ![image](https://private-user-images.githubusercontent.com/103084421/379730050-9399bfb6-c5f0-4d94-bdda-67d94b378609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjYyODcsIm5iZiI6MTcyOTc2NTk4NywicGF0aCI6Ii8xMDMwODQ0MjEvMzc5NzMwMDUwLTkzOTliZmI2LWM1ZjAtNGQ5NC1iZGRhLTY3ZDk0YjM3ODYwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMDMzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDNmMzI3YjRmYTNkOTNkZjEyZGZhNWRlNzA1YTQxOGMxYzY4N2NiMDcyZjdhNzFiOTVmMmQ1MzIxZTU2MTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pOfepkfMXxj_abTLw8m3XTCuAL7or-nUp28bdjOr9nU)
> 
> just prinnted nothing

Have you checked what is inside the exportPly/20 folder?

**Comment by Knni9ht** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/103084421/379730050-9399bfb6-c5f0-4d94-bdda-67d94b378609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjYyODcsIm5iZiI6MTcyOTc2NTk4NywicGF0aCI6Ii8xMDMwODQ0MjEvMzc5NzMwMDUwLTkzOTliZmI2LWM1ZjAtNGQ5NC1iZGRhLTY3ZDk0YjM3ODYwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxMDMzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDNmMzI3YjRmYTNkOTNkZjEyZGZhNWRlNzA1YTQxOGMxYzY4N2NiMDcyZjdhNzFiOTVmMmQ1MzIxZTU2MTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pOfepkfMXxj_abTLw8m3XTCuAL7or-nUp28bdjOr9nU)
> > 
> > 
> > just prinnted nothing
> 
> Have you checked what is inside the exportPly/20 folder?

yeah,there was an empty directory

**Comment by maturk** [comment]
This is the expected behaviour: 

<img width="576" alt="image" src="https://github.com/user-attachments/assets/9535310e-0cc3-4671-98aa-5ce0097b6a2f">

What does the command `ns-export --help` or `ns-export gaussian-splat --help` say? I am wondering if there are some problems with the nerfstudio installation

**Comment by Knni9ht** [comment]
![image](https://github.com/user-attachments/assets/c054a35d-844b-4db6-8eec-3f710017d1a9)

**Comment by maturk** [comment]
Can you run the command `ns-install-cli` and then try again. Also does training with dn-splatter work i.e. does `ns-train dn-splatter` work?

**Comment by Knni9ht** [comment]
![image](https://github.com/user-attachments/assets/701d9313-d5d5-405c-819f-dea19a848711)
train process worked

**Comment by Knni9ht** [comment]
![image](https://github.com/user-attachments/assets/64a274a4-52d5-448f-acee-6a67eb4e149f)
the command `ns-install-cli` did not work because i use windows?

**Comment by maturk** [comment]
I find it strange that ns-export is not working for you. This is expected output when running the command. I am not sure what is wrong, but I suspect somehow nerfstudio is not completely installed correctly, since the cli scripts are not working on your machine. But you also mentioned that you switched to some other conda environment (gsplat?) and you were able to run the ns-export command? Is my understanding correct?

<img width="576" alt="image" src="https://github.com/user-attachments/assets/62cf9502-71bc-4c4d-a383-798e475ba7cd">

**Comment by Knni9ht** [comment]
> I find it strange that ns-export is not working for you. This is expected output when running the command. I am not sure what is wrong, but I suspect somehow nerfstudio is not completely installed correctly, since the cli scripts are not working on your machine. But you also mentioned that you switched to some other conda environment (gsplat?) and you were able to run the ns-export command? Is my understanding correct?
> 
> <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/30566358/379734182-62cf9502-71bc-4c4d-a383-798e475ba7cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODE1ODAsIm5iZiI6MTczMDA4MTI4MCwicGF0aCI6Ii8zMDU2NjM1OC8zNzk3MzQxODItNjJjZjk1MDItNzFiYy00YzRkLWEzODMtNzk4ZTQ3NWJhN2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTA4YTE2ODRmMmU1OWRmY2JkYTQxZTUwZGM4ZDk0NDM4MTQ2MDA2OTY2YmI4OGFmYzA0YmI5MjljNWNjZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3P8SAvtkW18_oe2N5bigdP9AF6ATrveAaxDwv2NhEFc">

I fixed it by https://github.com/nerfstudio-project/nerfstudio/issues/3483#issuecomment-2430423841
