### ISSUE TITLE
Is transforms.json required for training?

### ISSUE THREAD

**Issue by seulqxq** [maturk/dn-splatter#86]
Hi, If I train with this command:

ns-train dn-splatter --data PATH_TO_DATA \
                 --pipeline.model.use-depth-loss True \
                 --pipeline.model.depth-lambda 0.2 \
                 --pipeline.model.use-normal-loss True \
                 --pipeline.model.use-normal-tv-loss True \
                 --pipeline.model.normal-supervision mono

Is transforms.json required for training?

**Comment by maturk** [comment]
transforms.json is not required if you have colmap processed data. In that case, you can use the cooler-map dataparser. 

```
ns-train dn-splatter 
coolermap --data PATH_TO_DATA
--pipeline.model.use-depth-loss True
--pipeline.model.depth-lambda 0.2
--pipeline.model.use-normal-loss True
--pipeline.model.use-normal-tv-loss True
--pipeline.model.normal-supervision mono
```

**Comment by seulqxq** [comment]
Ok, I will try, thanks for your quick reply!

**Comment by seulqxq** [comment]
I'm sorry to bother you again, but after using the above command, I get an error: Unrecognized or misplaced options. Is there a problem with my version?
![image](https://github.com/user-attachments/assets/ab4af2a2-ed75-48e0-9ca2-8c6776a1c599)

**Comment by maturk** [comment]
@seulqxq That is my bad. I gave the wrong command, the ordering is not correct. The ordering should be `ns-train method-name --options-for-method dataparser-name --data --options-for-data`. So the correct command is:

```
ns-train dn-splatter 
coolermap --data PATH_TO_DATA
--pipeline.model.use-depth-loss True
--pipeline.model.depth-lambda 0.2
--pipeline.model.use-normal-loss True
--pipeline.model.use-normal-tv-loss True
--pipeline.model.normal-supervision mono
```

**Comment by seulqxq** [comment]
Thanks for your reply!
Yes, the command you are providing is correct, but now I have another problem, that is, the amount of depth map (sfm_depths) and RGB image is not consistent, can you provide some advice?
I guess it is a COLMAP extraction problem, I will try to extract again and generate depth.
Thank you very much!
![image](https://github.com/user-attachments/assets/23c7e954-53d8-49b7-ae77-966f4dcb8a29)
