### ISSUE TITLE
Regarding the OOM issue, I would like to ask if it can be solved with multiple GPUs. What should I do if I can?

### ISSUE THREAD

**Issue by ruiqiyan** [maturk/dn-splatter#87]

**Comment by ruiqiyan** [comment]
> _未提供说明_

--machine.num-gpus 3。Is this directive possible?

**Comment by maturk** [comment]
Hi @ruiqiyan, training with multiple GPUs is not supported unfortunately. It is not entirely straightforward to implement this support, but it might be possible in the future.
