### ISSUE TITLE
AssertionError assert len(sfm_depth_filenames) == len(mono_depth_filenames)

### ISSUE THREAD

**Issue by ferryman123** [maturk/dn-splatter#98]
hi, when I use the command: python dn_splatter/scripts/align_depth.py --data [dataset] --no-skip-colmap-to-depths --no-skip-mono-depth-creation
I find some dataset that have the error 
Traceback (most recent call last):
  File "dn_splatter/scripts/align_depth.py", line 550, in <module>
    tyro.cli(ColmapToAlignedMonoDepths).main()
  File "dn_splatter/scripts/align_depth.py", line 123, in main
    assert len(sfm_depth_filenames) == len(mono_depth_filenames)

but other dataset doesnot have , I want to know why

**Comment by maturk** [comment]
This error most likely stems from the fact that your dataset consists of an "/images" folder that contains more images than what the colmap reconstruction (from the sparse/0 folder containing .bin /.txt files) has been able to register. So there is a mismatch in number of images and number of succesfully registered colmap images.

**Comment by Ioksiong** [comment]
> This error most likely stems from the fact that your dataset consists of an "/images" folder that contains more images than what the colmap reconstruction (from the sparse/0 folder containing .bin /.txt files) has been able to register. So there is a mismatch in number of images and number of succesfully registered colmap images.

Hi! I encountered the same issue, so how can I solve this problem? Do I need to manually delete the images in the "/images" folder that are not listed in the sparse/0/images.txt file, or do you have a better solution?
